package com.rngproduction.integrationCoreOW.configuration;

public enum TypeRq {
    PAYDOCACCEPT_GETDOCUMENTSRQ,
    PAYDOCACCEPT_PUTDOCUMENTSRQ,
    PAYDOCINFO_GETDOCUMENTSRQ,
    PAYDOCINFO_PUTDOCUMENTSRQ,
    ACCEPTPAY_GETDOCUMENTSRQ,
    ACCEPTPAY_PUTDOCUMENTSRQ,
    EXECPAY_GETDOCUMENTSRQ,
    EXECPAY_PUTDOCUMENTSRQ
}
